#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/switchbot-common"

while getopts d:a: option
do
  case "${option}"
    in
    d) deviceid=${OPTARG};;
    a) action=${OPTARG};;
  esac
done
# arg check
if test -z $deviceid || test -z $action;
then
  echo "Usage $0 -d <deviceid> -a <action>"
  exit 1;
fi
command='{"command": "setAll","parameter": "'$action'","commandType": "command"}'

switchbot_post "/devices/${deviceid}/commands" "${command}" | jq
