#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/switchbot-common"

while getopts d:c: option
do
  case "${option}"
    in
    d) deviceid=${OPTARG};;
    c) custom=${OPTARG};;
  esac
done
# arg check
if test -z $deviceid || test -z $custom;
then
  echo "Usage $0 -d <deviceid> -c <custom>"
  exit 1;
fi
command='{"command":"'$custom'","parameter":"default","commandType":"customize"}'

switchbot_post "/devices/${deviceid}/commands" "${command}" | jq
