#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/switchbot-common"

while getopts d:c: option
do
  case "${option}"
    in
    d) deviceid=${OPTARG};;
    c) channel=${OPTARG};;
  esac
done
# arg check
if test -z $deviceid || test -z $channel;
then
  echo "Usage $0 -d <deviceid> -c <channel>"
  exit 1;
fi
command='{"command": "SetChannel","parameter": "'$channel'","commandType": "command"}'

switchbot_post "/devices/${deviceid}/commands" "${command}" | jq
