#!/bin/bash
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
. "$SCRIPT_DIR/switchbot-common"

while getopts d:c: option
do
  case "${option}"
    in
    d) deviceid=${OPTARG};;
    c) com=${OPTARG};;
  esac
done
# arg check
if test -z $deviceid || test -z $com;
then
  echo "Usage $0 -d <deviceid> -c <command>"
  exit 1;
fi
command='{"command": "'$com'","parameter": "default","commandType": "command"}'

switchbot_post "/devices/${deviceid}/commands" "${command}" | jq
